// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWAYco8Nejsm8u35HPbzMHDi5b1Dwuduw',
    appId: '1:250697133179:web:a906f6a6e14574741fc6de',
    messagingSenderId: '250697133179',
    projectId: 'chat-setup-95788',
    authDomain: 'chat-setup-95788.firebaseapp.com',
    storageBucket: 'chat-setup-95788.appspot.com',
    measurementId: 'G-86NWB76YC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdjJE9qoao2MKCxRPUbFC-2oMIMfGeV8',
    appId: '1:250697133179:android:089f34e8e29222ab1fc6de',
    messagingSenderId: '250697133179',
    projectId: 'chat-setup-95788',
    storageBucket: 'chat-setup-95788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxmONL5QJ4HbtYTE1ufb6qH0DxMYw1krs',
    appId: '1:250697133179:ios:9332728edc6f3df51fc6de',
    messagingSenderId: '250697133179',
    projectId: 'chat-setup-95788',
    storageBucket: 'chat-setup-95788.appspot.com',
    iosBundleId: 'com.example.chatSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxmONL5QJ4HbtYTE1ufb6qH0DxMYw1krs',
    appId: '1:250697133179:ios:0b0f6e5302380c871fc6de',
    messagingSenderId: '250697133179',
    projectId: 'chat-setup-95788',
    storageBucket: 'chat-setup-95788.appspot.com',
    iosBundleId: 'com.example.chatSetup.RunnerTests',
  );
}
